# Generated by Django 5.0.4 on 2024-08-01 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('servicos', models.IntegerField()),
                ('idcnpj_cliente', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=45)),
                ('tipo_de_executante', models.IntegerField(choices=[(1, 'Mecânico'), (2, 'Elétrico'), (3, 'Civil')], default=1)),
                ('grau_de_urgencia', models.IntegerField(choices=[(1, 'Urgente'), (2, 'Data marcada'), (3, ' ')], default=1)),
                ('nome_do_solicitante', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServicosPrestados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico_prestados', models.CharField(max_length=100)),
                ('data_de_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_de_termino', models.DateTimeField(auto_now_add=True)),
                ('status_da_obra', models.IntegerField(choices=[(3, 'Finalizado'), (2, 'Em andamento'), (1, 'Aguardando aprovação')], default=1)),
                ('tipo_de_servico', models.IntegerField(choices=[(1, 'Mecânico'), (2, 'Elétrico'), (3, 'Civil')], default=1)),
                ('custo_da_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atualizacao_da_obra', models.CharField(max_length=255)),
                ('servicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concept_app.cliente')),
            ],
        ),
    ]
