# Generated by Django 5.0.4 on 2024-08-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concept_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicosprestados',
            name='status_da_obra',
            field=models.IntegerField(choices=[(1, 'Aguardando aprovação'), (2, 'Em andamento'), (3, 'Finalizado')], default=1),
        ),
        migrations.AlterField(
            model_name='servicosprestados',
            name='tipo_de_servico',
            field=models.IntegerField(choices=[(3, 'Civil'), (1, 'Mecânico'), (2, 'Elétrico')], default=1),
        ),
    ]
