# Generated by Django 5.0.4 on 2024-08-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concept_app', '0002_alter_servicosprestados_status_da_obra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicosprestados',
            name='tipo_de_servico',
            field=models.IntegerField(choices=[(1, 'Mecânico'), (3, 'Civil'), (2, 'Elétrico')], default=1),
        ),
    ]
