# Generated by Django 5.1 on 2024-08-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concept_app', '0003_alter_servicosprestados_tipo_de_servico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicosprestados',
            old_name='servicos',
            new_name='idcnpj_cliente',
        ),
        migrations.RemoveField(
            model_name='servicosprestados',
            name='atualizacao_da_obra',
        ),
        migrations.RemoveField(
            model_name='servicosprestados',
            name='servico_prestados',
        ),
        migrations.AlterField(
            model_name='servicosprestados',
            name='status_da_obra',
            field=models.IntegerField(choices=[(2, 'Em andamento'), (3, 'Finalizado'), (1, 'Aguardando aprovação')], default=1),
        ),
        migrations.AlterField(
            model_name='servicosprestados',
            name='tipo_de_servico',
            field=models.IntegerField(choices=[(1, 'Mecânico'), (2, 'Elétrico'), (3, 'Civil')], default=1),
        ),
    ]
